export const TabsJson = [
  {
    data: [
      {
        module_id: 14,
        name: 'Personal Profile',
        app_forms: null,
        candidate_forms: 'candidate_profile',
        post_module_id: 50002,
        module_type: 2,
        module_data: null,
        message: 'demo ',
        note: 'Note- Description',
        warning: null,
        specializations: ['new', 'demo'],
        cdid: null,
        data_status: 1,
      },
      {
        module_id: 15,
        name: 'Contact Details',
        app_forms: null,
        candidate_forms: 'candidate_address',
        post_module_id: 50003,
        module_type: 1,
        module_data: null,
        message: 'This is new entry ',
        note: 'Note- Description',
        warning: 'this is warning',
        specializations: ['We have new '],
        cdid: null,
        data_status: null,
      },
      {
        module_id: 1,
        name: 'PH Suitability',
        app_forms: null,
        candidate_forms: null,
        post_module_id: 11389,
        module_type: 1,
        module_data: {
          pm_phsuitablities: {
            phsuitability: ['5', '3'],
            registrationid: '3',
          },
        },
        message: null,
        warning: null,
        note: 'Note- Description',
        specializations: null,
        cdid: null,
        data_status: null,
      },
      {
        module_id: 16,
        name: 'Age Relaxation',
        app_forms: 'app_agerelax',
        candidate_forms: null,
        post_module_id: null,
        module_type: null,
        module_data: null,
        message: null,
        warning: null,
        note: 'Note- Description',
        specializations: null,
        cdid: null,
        data_status: null,
      },
      {
        module_id: 3,
        name: 'Education Qualification',
        app_forms: 'app_qualifications',
        candidate_forms: 'candidate_qualifications',
        post_module_id: 11400,
        module_type: 1,
        module_data: {
          pm_eq_qualifications: {
            registrationid: '3',
            eq_qualifications: ['16', '18'],
          },
        },
        message: 'demo9',
        warning: 'demo9',
        note: 'Note- Description',
        specializations: ['this is special'],
        cdid: null,
        data_status: null,
      },
      {
        module_id: 5,
        name: 'Experience',
        app_forms: 'app_experiences',
        candidate_forms: 'candidate_experiences',
        post_module_id: 11402,
        module_type: 1,
        module_data: {
          pm_exp_master: {
            employment_type: ['03'],
            experience_category: ['2'],
          },
        },
        message: null,
        warning: null,
        note: 'Note- Description',
        specializations: null,
        cdid: null,
        data_status: null,
      },
      {
        module_id: 21,
        name: 'Payment Entry',
        app_forms: 'app_payment',
        candidate_forms: null,
        post_module_id: null,
        module_type: null,
        module_data: null,
        message: null,
        warning: null,
        note: 'Note- Description',
        specializations: null,
        cdid: null,
        data_status: null,
      },
      {
        module_id: 13,
        name: 'Recruitment Test Centre',
        app_forms: 'app_centers',
        candidate_forms: null,
        post_module_id: 11401,
        module_type: 1,
        module_data: {
          pm_centers: {
            centers: ['45', '47', '1'],
            registrationid: '3',
          },
        },
        message: null,
        warning: null,
        note: 'Note- Description',
        specializations: null,
        cdid: null,
        data_status: null,
      },
      {
        module_id: 19,
        name: 'Fee Exemption',
        app_forms: null,
        candidate_forms: '',
        post_module_id: null,
        module_type: null,
        module_data: null,
        message: null,
        warning: null,
        note: 'Note- Description',
        specializations: null,
        cdid: null,
        data_status: null,
      },
      {
        module_id: 20,
        name: 'Photo and Signature Upload',
        app_forms: null,
        candidate_forms: 'candidate_photosign',
        post_module_id: null,
        module_type: null,
        module_data: null,
        message: null,
        warning: null,
        note: 'Note- Description',
        specializations: null,
        cdid: null,
        data_status: null,
      },
      {
        module_id: 25,
        name: 'Upload Documents',
        app_forms: 'app_documents',
        candidate_forms: 'candidate_uploaddoc',
        post_module_id: 11399,
        module_type: 2,
        module_data: null,
        message: null,
        warning: null,
        note: 'Note- Description',
        specializations: null,
        cdid: null,
        data_status: null,
      },
    ],
    message: 'application response',
    post_info: 'Post Name',
  },
]
