export const candidateData = [
  {
    formid: 'candidate_login',
    title: 'Candidate Login',
    type: 'M',
    module: 'candidate',
    pkeys: null,
    pkeyid: null,
    model: null,
    extra_props: null,
    readonly: null,
    colsize: 'col-12',
    classes: null,
    hint: null,
    sortno: null,
    active: 1,
    formview: 'form',
    formfilter: null,
    description: null,
    formgroup: null,
    icon: null,
    sections: [
      {
        columns: [
          {
            formid: 'candidate_login',
            sectionid: null,
            field: 'login_type',
            title: 'Select Mode for Login',
            colsize: 'col-12',
            type: 'select',
            component: 'reactselect',
            required: 1,
            sortno: 1,
            active: 1,
            formview: 1,
            listview: null,
            options: {
              data: [
                {
                  label: 'Registration ID',
                  value: 'registrationid',
                },
                {
                  label: 'Email',
                  value: 'email',
                },
                {
                  label: 'Mobile',
                  value: 'mobile',
                },
              ],
            },
            defaultvalue: null,
            addattrs: null,
            readonly: null,
            hidden: null,
            classes: null,
            inline: 0,
            placeholder: null,
            hint: null,
            dt_width: null,
            dt_sortable: null,
            dt_callback: null,
            dt_class: null,
            dt_rander: null,
            dt_rowgroup: null,
            dt_filter: null,
            dbfield: null,
            info: null,
            title_lng: '',
            printview: null,
            printview_spl: 0,
          },
          {
            formid: 'candidate_login',
            sectionid: null,
            field: 'registrationid',
            title: 'Enter ID',
            colsize: 'col-12',
            type: 'registration',
            component: 'input-mask',
            required: 1,
            sortno: 2,
            active: 1,
            formview: 1,
            listview: null,
            selectqry: null,
            options: null,
            defaultvalue: null,
            addattrs: null,
            readonly: null,
            hidden: null,
            classes: null,
            inline: 0,
            placeholder: null,
            hint: null,
            dt_width: null,
            dt_sortable: null,
            dt_callback: null,
            dt_class: null,
            dt_rander: null,
            dt_rowgroup: null,
            dt_filter: null,
            dbfield: null,
            info: null,
            title_lng: '',
            printview: null,
            printview_spl: 0,
          },
          {
            formid: 'candidate_login',
            sectionid: null,
            field: 'email',
            title: 'Enter Email Id ',
            colsize: 'col-12',
            type: 'email',
            component: 'verify-input',
            required: 1,
            sortno: 3,
            active: 1,
            formview: 1,
            listview: null,
            selectqry: null,
            options: null,
            defaultvalue: null,
            addattrs: null,
            readonly: null,
            hidden: null,
            classes: null,
            inline: 0,
            placeholder: null,
            hint: null,
            dt_width: null,
            dt_sortable: null,
            dt_callback: null,
            dt_class: null,
            dt_rander: null,
            dt_rowgroup: null,
            dt_filter: null,
            dbfield: null,
            info: null,
            title_lng: '',
            printview: null,
            printview_spl: 0,
          },
          {
            formid: 'candidate_login',
            sectionid: null,
            field: 'mobile',
            title: 'Enter Moble Number',
            colsize: 'col-12',
            type: 'mobile',
            component: 'verify-input',
            required: 1,
            sortno: 3,
            active: 1,
            formview: 1,
            listview: null,
            selectqry: null,
            options: null,
            defaultvalue: null,
            addattrs: {
              mask: /^[1-9]\d{0,9}$/,
            },
            readonly: null,
            hidden: null,
            classes: null,
            inline: 0,
            placeholder: null,
            hint: null,
            dt_width: null,
            dt_sortable: null,
            dt_callback: null,
            dt_class: null,
            dt_rander: null,
            dt_rowgroup: null,
            dt_filter: null,
            dbfield: null,
            info: null,
            title_lng: '',
            printview: null,
            printview_spl: 0,
          },
          {
            formid: 'candidate_login',
            sectionid: null,
            field: 'password',
            title: 'Password',
            colsize: 'col-12',
            type: 'password',
            component: 'input',
            required: 1,
            sortno: 4,
            active: 1,
            formview: 1,
            listview: null,
            selectqry: null,
            options: null,
            defaultvalue: null,
            addattrs: null,
            readonly: null,
            hidden: null,
            classes: null,
            inline: 0,
            placeholder: null,
            hint: null,
            dt_width: null,
            dt_sortable: null,
            dt_callback: null,
            dt_class: null,
            dt_rander: null,
            dt_rowgroup: null,
            dt_filter: null,
            dbfield: null,
            info: null,
            title_lng: '',
            printview: null,
            printview_spl: 0,
          },
          {
            formid: 'candidate_login',
            sectionid: null,
            field: 'captcha',
            title: 'Captcha',
            colsize: 'col-12',
            type: 'string',
            component: 'captcha',
            required: 1,
            sortno: 5,
            active: 1,
            formview: 1,
            listview: null,
            selectqry: null,
            options: null,
            defaultvalue: null,
            addattrs: null,
            readonly: null,
            hidden: null,
            classes: null,
            inline: 0,
            placeholder: null,
            hint: null,
            dt_width: null,
            dt_sortable: null,
            dt_callback: null,
            dt_class: null,
            dt_rander: null,
            dt_rowgroup: null,
            dt_filter: null,
            dbfield: null,
            info: null,
            title_lng: '',
            printview: null,
            printview_spl: 0,
          },
        ],
      },
    ],
  },
]
